[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.obj.products"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Hubspot", "CRM", "Object", "Products"] 
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.products"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
